workflows:
  ios-build:
    name: Empire Equipment iOS (Unsigned)
    environment:
      xcode: latest
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap add ios || echo "iOS platform already exists"
          npx cap sync ios

      - name: Build iOS app (Unsigned)
        script: |
          cd ios
          xcodebuild -workspace App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/EmpireEquipment.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Package app manually (skip exportArchive)
        script: |
          mkdir -p $CM_BUILD_DIR/unsigned_ipa
          cd $CM_BUILD_DIR/EmpireEquipment.xcarchive/Products/Applications
          appname=$(ls | grep ".app$")
          echo "Zipping $appname into unsigned IPA..."
          cd ..
          mkdir Payload
          mv Applications/$appname Payload/
          zip -r $CM_BUILD_DIR/unsigned_ipa/EmpireEquipment-unsigned.ipa Payload
          echo "✅ Unsigned .ipa created at: $CM_BUILD_DIR/unsigned_ipa/EmpireEquipment-unsigned.ipa"

    artifacts:
      - $CM_BUILD_DIR/unsigned_ipa/*.ipa

    publishing:
      email:
        recipients:
          - info@empire-schools.com
        notify:
          success: true
          failure: true
