workflows:
  android-build:
    name: Empire Equipment Android (Fire Tablet Ready)
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap add android || echo "Android platform already exists"
          npx cap sync android

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
          echo "✅ Android APK built successfully."

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - info@empire-schools.com
        notify:
          success: true
          failure: true
